- name: Download repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: Copy vault config
  ansible.builtin.copy:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: Open Vault port 8200 in firewalld
  ansible.posix.firewalld:
    port: 8200/tcp
    permanent: yes
    state: enabled
    immediate: yes
    
- name: Start Vault service
  ansible.builtin.systemd_service:
    name: vault
    state: started
    enabled: yes